apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  01-init-app-user.js: |
    db = db.getSiblingDB('admin');
    db.createUser({
      user: '${MONGO_APP_USERNAME}',
      pwd: '${MONGO_APP_PASSWORD}',
      roles: [
        { role: 'readWrite', db: 'myappdb' }
      ]
    });
